### ISSUE TITLE
migration 4.4.0 to 4.5.2

### ISSUE THREAD

**Issue by hasanmumin** [NewtronLabs/IpcEventBus#1]
Hi,
i try to usage this library but it look like Data,IData, EventExample classes removed from new version. 

How i can try your example with new version ?

**Comment by NewtronLabs** [comment]
Hello @hasanmumin, 

We see that you closed your question. However, we would still like to provide some support. `Data`, `IData`, and `EventExample` are part of the sample project for testing the features of IpcEventBus. We encourage you to use that sample and define your own events and data  to transfer over IPC. 

We hope this addresses your question. 

Regards,
Newtron Labs Community Outreach Team
