### ISSUE TITLE
Unable to run demo(App2)

### ISSUE THREAD

**Issue by sallybox520** [NewtronLabs/IpcEventBus#3]
When I compiled and ran App2, I saw the following error :
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.newtronlabs.ipceventbus.app2, PID: 1962
java.lang.NoSuchMethodError: No static method getInstance()Lcom/newtronlabs/ipceventbus/connection/factory/ConnectorFactory; in class 
Lcom/newtronlabs/ipceventbus/connection/factory/ConnectorFactory; or its super classes (declaration of 'com.newtronlabs.ipceventbus.connection.factory
.ConnectorFactory' appears in /data/app/com.newtronlabs.ipceventbus.app2-2/base.apk)
        at com.newtronlabs.ipceventbus.app2.MainActivity.onCreate(MainActivity.java:38)
        at android.app.Activity.performCreate(Activity.java:6222)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
... ...
... ...

But I didn't make any changes to the example...

// build.gradle(App2)
buildscript {
    repositories {
        google()
        jcenter()
        maven { url "http://code.newtronlabs.com:8081/artifactory/libs-release-local" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.2'
        classpath "com.newtronlabs.android:plugin:4.0.0"
    }
}
... ...

// build.gradle(:app)
dependencies {
    ... ...

    // IPC EventBus.
    compileOnly 'com.newtronlabs.ipceventbus:ipceventbus:6.0.0'
    implementation project(path: ':events')
}

// build.gradle(:events)
dependencies {
    ... ...

    // IPC EventBus.
    compileOnly 'com.newtronlabs.ipceventbus:ipceventbus:6.0.0'
}

**Comment by NewtronLabs** [comment]
Hi @sallybox520,

I've communicated this issue to the Android team. We will get back to you with a solution ASAP.

Thanks for reporting it,
Amy

**Comment by NewtronLabs** [comment]
Hi @sallybox520,

We have released a new version to address this issue.

Please use: `compileOnly 'com.newtronlabs.ipceventbus:ipceventbus:6.0.1'`

We also updated the sample projects. Let us know if you run into any other issues.

Thanks,
Amy

**Comment by sallybox520** [comment]
Cool that looks like it's working, Thx!
