### ISSUE TITLE
Problem with android studio 4

### ISSUE THREAD

**Issue by gilshallem** [NewtronLabs/IpcEventBus#4]
After upgrading android studio i get this error:
`Could not find com.newtronlabs.android:plugin:4.0.1.
Searched in the following locations:
  - https://jcenter.bintray.com/com/newtronlabs/android/plugin/4.0.1/plugin-4.0.1.pom
  - https://dl.google.com/dl/android/maven2/com/newtronlabs/android/plugin/4.0.1/plugin-4.0.1.pom
  - https://maven.fabric.io/public/com/newtronlabs/android/plugin/4.0.1/plugin-4.0.1.pom
  - https://dl.bintray.com/ironsource-mobile/android-sdk/com/newtronlabs/android/plugin/4.0.1/plugin-4.0.1.pom
  - http://code.newtronlabs.com:8081/artifactory/libs-release-local/com/newtronlabs/android/plugin/4.0.1/plugin-4.0.1.pom
Required by:
    project :`

**Comment by NewtronLabs** [comment]
Hi @gilshallem,

We are investigating the issue. Could you send us your `gradle` file that includes the plugin?

Thanks,
Amy

**Comment by NewtronLabs** [comment]
Closing this issue because client never responded.
