### ISSUE TITLE
How to use this to communicate with a service in different/isolated process?

### ISSUE THREAD

**Issue by febryanasaperdana** [NewtronLabs/IpcEventBus#5]
Can you help me to implement this to communicate with a service in different/isolated process?
your sample is app-to-app, and I think it's lacking.
This library is very great and has a massive potential, in case there's more examples and guidelines.
Please help.

**Comment by NewtronLabs** [comment]
Hi @febryanasaperdana !

The library works with different isolated processes. You can have these processes in different apps or in the same app. In the sample app you have to provide the process name "com.myapp.processName" if you do that with the name of the process that you have it will work. Let me know if you still need more help, we are here to help you.

Regards,
Amy
