### ISSUE TITLE
Event IData size limit

### ISSUE THREAD

**Issue by Lishen1** [NewtronLabs/IpcEventBus#6]
Intents has limit of 1MB. What a limit for IpcEventBus? Can I use it for full HD images exchanging?

**Comment by NewtronLabs** [comment]
Hi @Lishen1,

Yes, IpcEventBus has a 1MB limit. Look at https://github.com/NewtronLabs/SharedMemory for unlimited.

**Comment by Lishen1** [comment]
Thanks!
