### ISSUE TITLE
Request to have app upgrade to latest Gradle

### ISSUE THREAD

**Issue by eaaliprantis** [NewtronLabs/IpcEventBus#8]
Hi,

So i was planning on using the IpcEventBus (and possibly others) in an application that i am working on.  And I keep getting an issue with gradle wanting version 3.5.+ and not any of the latest version of gradle (version 4.0.1, as an example).  Is there any timeline if this plan to support latest gradle / v4 would occur?

Best, 

Manny

**Comment by NewtronLabs** [comment]
Hi Manny,

We are glad that you are interested! We have a version in the works. However, due to a lack of bandwidth with other projects this release may take a bit longer than expected. For now you might want to use a lower version of gradle.

Regards,
Amy

**Comment by NewtronLabs** [comment]
Hi @eaaliprantis,

Version `6.0.2-alpha08` works with gradle `7.0.4`.

Cheers,
Amy
